name: 'publish'

on:
  push:
    branches:
      - release

jobs:
  publish-flutter:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.3
      - name: Check Flutter
        run: flutter --version
      - name: Install Dependencies
        run: flutter pub get 
      - name: Build APK
        run: flutter build apk --release
      - name: Extract version from pubspec.yaml
        id: get_version 
        run: |
          echo "::set-output name=version::$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/app-release.apk
          asset_name: ${{ github.event.repository.name }}${{ steps.get_version.outputs.version }}
          tag: ${{ steps.get_version.outputs.version }}
      # - uses: tauri-apps/tauri-action@v0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
      #     releaseName: 'App v__VERSION__'
      #     releaseBody: 'See the assets to download this version and install.'
      #     releaseDraft: true
      #     prerelease: false
      #     args: ${{ matrix.args }}
